# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: 'windows-2019'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    #testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CmdLine@2
  inputs:
    script: mvn clean install
  displayName: 'Run Script'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/target/failsafe-reports/TEST-starter.CucumberTestSuite.xml'
    mergeTestResults: true
  continueOnError: true
  condition: always()

- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '**/nss-qa-ui-testing-serenity-BDD/target/site/serenity/index.html'
    artifact: 'HTML Report'
  continueOnError: true
  condition: always()